

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url : jdbc:h2:mem:blog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
sihyeon:
  jwt-Key : "MrBSSdpIcdVtFw6ERE77Nev1MeoM7U5sumaSXvbuqpc="
server:
  port: 8888
  address: 0.0.0.0
