
### 게시글 작성

POST http://localhost:8888/posts
Content-Type: application/json

{
  "title" : "제목",
  "content" : "내용"
}

### 게시글 삭제
DELETE http://localhost:8888/posts/1
Content-Type: application/json

###

GET http://localhost:8888/subscribe/1
Content-Type: application/json

###

POST http://localhost:8888/posts/1/comments
Content-Type: application/json

{
  "author" : "제목1",
  "password" : "111167",
  "content" : "제발제발제발제발제발제발제발"
}

### 게시글 리스트 조회
GET http://localhost:8888/posts?page=1&size=2
Content-Type: application/json